import Colors from '../Colors';
import {StyleSheet} from 'react-native';

const ButtonStyle = StyleSheet.create({
  defaultText: {
    color: 'white',
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    textAlignVertical: 'center',
    lineHeight: 20,
    marginHorizontal: 8,
  },
  defaultIcon: {
    color: 'white',
  },
  primaryText: {
    color: Colors.Primary_70,
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    textAlignVertical: 'center',
    lineHeight: 20,
    marginHorizontal: 8,
  },
  primaryIcon: {
    color: Colors.Primary_70,
  },
  secondaryText: {
    color: Colors.Secondary_70,
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    textAlignVertical: 'center',
    lineHeight: 20,
    marginHorizontal: 8,
  },
  secondaryIcon: {
    color: Colors.Secondary_70,
  },
  blackText: {
    color: Colors.Black_100,
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    textAlignVertical: 'center',
    lineHeight: 20,
    marginHorizontal: 8,
  },
  blackIcon: {
    color: Colors.Black_100,
  },
  primaryLargeFull: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Primary_70,
  },
  primaryLargeFlex: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Primary_70,
    alignSelf: 'flex-start',
  },
  primarySmallFull: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Primary_70,
  },
  primarySmallFlex: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Primary_70,
    alignSelf: 'flex-start',
  },
  secondaryLargeFull: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Secondary_70,
  },
  secondaryLargeFlex: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Secondary_70,
    alignSelf: 'flex-start',
  },
  secondarySmallFull: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Secondary_70,
  },
  secondarySmallFlex: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Secondary_70,
    alignSelf: 'flex-start',
  },
  secondary: {
    padding: 16,
    backgroundColor: Colors.Secondary_70,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  blackLargeFull: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Black_100,
  },
  blackLargeFlex: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Black_100,
    alignSelf: 'flex-start',
  },
  blackSmallFull: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Black_100,
  },
  blackSmallFlex: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.Black_100,
    alignSelf: 'flex-start',
  },
  whiteLargeFull: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  whiteLargeFlex: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
  },
  whiteSmallFull: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  whiteSmallFlex: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
  },
  outlinePrimaryLargeFull: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: Colors.Primary_70,
  },
  outlinePrimaryLargeFlex: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.Primary_70,
  },
  outlinePrimarySmallFull: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: Colors.Primary_70,
  },
  outlinePrimarySmallFlex: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.Primary_70,
  },
  outlineSecondaryLargeFull: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: Colors.Secondary_70,
  },
  outlineSecondaryLargeFlex: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.Secondary_70,
  },
  outlineSecondarySmallFull: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: Colors.Secondary_70,
  },
  outlineSecondarySmallFlex: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.Secondary_70,
  },
  outlineBlackLargeFull: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: Colors.Black_100,
  },
  outlineBlackLargeFlex: {
    padding: 16,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.Black_100,
  },
  outlineBlackSmallFull: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: Colors.Black_100,
  },
  outlineBlackSmallFlex: {
    padding: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.Black_100,
  },
  customOutlinePrimaryXSmallFlex: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.Primary_70,
  },
  customPrimarySmallText: {
    color: Colors.Primary_70,
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    textAlignVertical: 'center',
    lineHeight: 20,
    marginHorizontal: 8,
  },
});

export default ButtonStyle;
// alignSelf: 'flex-start',
